---
# vim: foldmarker=[[[,]]]:foldmethod=marker

- name: Ensure gdm3 directory is present
  file:
    path: '/etc/gdm3'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Divert GDM configuration
  command: dpkg-divert --quiet --local --divert "{{ item }}.dpkg-divert"
           --rename "{{ item }}"
  args:
    creates: '{{ item }}.dpkg-divert'
  with_items:
    - '/etc/gdm3/daemon.conf'
    - '/etc/gdm3/greeter.dconf-defaults'

- name: Configure GDM
  template:
    src: 'etc/gdm3/daemon.conf.j2'
    dest: '/etc/gdm3/daemon.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart display-manager' ]

- name: Configure dconf defaults
  template:
    src: 'etc/gdm3/greeter.dconf-defaults.j2'
    dest: '/etc/gdm3/greeter.dconf-defaults'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart display-manager' ]
