---
# vim: foldmarker=[[[,]]]:foldmethod=marker

## https://wiki.ubuntu.com/LightDM
## Configuration order:
## /usr/share/lightdm/lightdm.conf.d/*.conf
## /etc/lightdm/lightdm.conf.d/*.conf
## /etc/lightdm/lightdm.conf

- name: Ensure lightdm.conf.d directory is present
  file:
    path: '/etc/lightdm/lightdm.conf.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Divert LightDM configuration
  community.general.dpkg_divert:
    path: '/etc/lightdm/lightdm-gtk-greeter.conf'
    state: 'present'
  when: not (dm__testing_mode|d(False) | bool)

- name: Configure LightDM
  template:
    src: 'etc/lightdm/lightdm.conf.d/local.conf.j2'
    dest: '/etc/lightdm/lightdm.conf.d/10_ypid_dm.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart display-manager' ]

- name: Configure LightDM greeter
  template:
    src: 'etc/lightdm/lightdm-gtk-greeter.conf.j2'
    dest: '/etc/lightdm/lightdm-gtk-greeter.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart display-manager' ]

- block:

    - name: Copy file gnome-classic.desktop to gnome-classic.desktop.bak (xsessions)
      copy: remote_src=True src=/usr/share/xsessions/gnome-classic.desktop  dest=/usr/share/xsessions/gnome-classic.desktop.bak
    - name: Remove gnome-classic.desktop (xsessions)
      file: path=/usr/share/xsessions/gnome-classic.desktop state=absent

    - name: Copy file gnome-classic.desktop to gnome-classic.desktop.bak (wayland-sessions)
      copy: remote_src=True src=/usr/share/wayland-sessions/gnome-classic.desktop  dest=/usr/share/wayland-sessions/gnome-classic.desktop.bak
    - name: Remove gnome-classic.desktop (wayland-sessions)
      file: path=/usr/share/wayland-sessions/gnome-classic.desktop state=absent

    - name: Copy file gnome.desktop to gnome.desktop.bak (xsessions)
      copy: remote_src=True src=/usr/share/xsessions/gnome.desktop  dest=/usr/share/xsessions/gnome.desktop.bak
    - name: Remove gnome.desktop (xsessions)
      file: path=/usr/share/xsessions/gnome.desktop state=absent

    - name: Copy file gnome.desktop to gnome.desktop.bak (wayland-sessions)
      copy: remote_src=True src=/usr/share/wayland-sessions/gnome.desktop  dest=/usr/share/wayland-sessions/gnome.desktop.bak
    - name: Remove gnome.desktop (wayland-sessions)
      file: path=/usr/share/wayland-sessions/gnome.desktop state=absent

  ignore_errors: true

