---
# vim: foldmarker=[[[,]]]:foldmethod=marker

## https://wiki.ubuntu.com/LightDM
## Configuration order:
## /usr/share/lightdm/lightdm.conf.d/*.conf
## /etc/lightdm/lightdm.conf.d/*.conf
## /etc/lightdm/lightdm.conf

- name: Ensure lightdm.conf.d directory is present
  file:
    path: '/etc/lightdm/lightdm.conf.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Divert LightDM configuration
  dpkg_divert:
    path: '/etc/lightdm/lightdm-gtk-greeter.conf'
    state: 'present'
  when: not (dm__testing_mode|d(False) | bool)

- name: Configure LightDM
  template:
    src: 'etc/lightdm/lightdm.conf.d/local.conf.j2'
    dest: '/etc/lightdm/lightdm.conf.d/10_ypid_dm.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart display-manager' ]

- name: Configure LightDM greeter
  template:
    src: 'etc/lightdm/lightdm-gtk-greeter.conf.j2'
    dest: '/etc/lightdm/lightdm-gtk-greeter.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart display-manager' ]
