---
# vim: foldmarker=[[[,]]]:foldmethod=marker

- name: Ensure specified packages are in there desired state
  package:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - '{{ dm__packages }}'
    - '{{ dm__package_map[dm__name] }}'
    - '{{ dm__lightdm_packages if (dm__name == "lightdm") else [] }}'
    - '{{ dm__gdm_packages if (dm__name == "gdm") else [] }}'
  tags: [ 'role::dm:pkg' ]

- include: 'gdm.yml'
  when: (dm__name == "gdm")

- include: 'lightdm.yml'
  when: (dm__name == "lightdm")

- name: Configure default display manager in debconf
  debconf:
    name: 'shared'
    question: 'shared/default-x-display-manager'
    vtype: 'select'
    value: '{{ dm__name }}'

- name: Configure default display manager in X11
  template:
    src: 'etc/X11/default-display-manager.j2'
    dest: '/etc/X11/default-display-manager'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Configure default display manager in systemd
  file:
    src: '/lib/systemd/system/{{ dm__package_map[dm__name] }}.service'
    dest: '/etc/systemd/system/display-manager.service'
    state: 'link'
  when: (ansible_distribution|d("") == 'Debian' and
         ansible_distribution_release|d("") == 'jessie')

- name: Configure default session manager
  alternatives:
    name: 'x-session-manager'
    path: '{{ dm__session_manager }}'
  when: dm__session_manager != omit
